In [1]:
import numpy as np

In [19]:
x=np.array([1,2,3,6,8,9])
x

array([1, 2, 3, 6, 8, 9])

In [20]:
x.shape
#3 elements in array. One domensional array

(6,)

In [21]:
x.size

6

In [22]:
x[2,]

3

In [23]:
x[1]

2

In [24]:
x[:4]

array([1, 2, 3, 6])

In [25]:
x[4:]

array([8, 9])

In [26]:
np.save('x',x)

In [28]:
np.load('x.npy')

array([1, 2, 3, 6, 8, 9])